{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "todo-app.fullname" . }}-ingress
  labels:
    {{- include "todo-app.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                {{- if eq .service "frontend" }}
                name: {{ include "todo-app.fullname" $ }}-frontend
                port:
                  number: {{ $.Values.frontend.port }}
                {{- else if eq .service "backend" }}
                name: {{ include "todo-app.fullname" $ }}-backend
                port:
                  number: {{ $.Values.backend.port }}
                {{- end }}
          {{- end }}
    {{- end }}
{{- end }}
